# Константы и настройки
QUANTITY_OF_BLOCKS_IN_ITERATION = 10
MAX_ITERATIONS = 10000
REQUESTS_QUANTITY = 800
MIN_VALUE_THRESHOLD = 0.01
MAX_LINES_IN_TX_CACHE = 100000
MAX_LINES_IN_HASH_CACHE = 0
START_BLOCK = 770000
MAX_SAVE_TASKS = 10

# Список проблемных блоков, если есть
PROBLEM_BLOCKS_LIST = 0