"""Regenerate requirements.lock.txt from the selected Python environment."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


DEFAULT_EXCLUDED_PACKAGES: set[str] = set()


def project_root() -> Path:
    return Path(__file__).resolve().parents[1]


def lock_header() -> str:
    excluded = ", ".join(sorted(DEFAULT_EXCLUDED_PACKAGES)) or "none"
    return (
        "# Generated by scripts/update_requirements_lock.py\n"
        "# Run with the intended project virtual environment.\n\n"
        f"# Excluded from freeze: {excluded}\n\n"
    )


def is_virtual_environment() -> bool:
    return sys.prefix != sys.base_prefix


def collect_freeze() -> str:
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--local"],
        check=True,
        capture_output=True,
        text=True,
    )
    lines = [
        line.strip()
        for line in result.stdout.splitlines()
        if line.strip()
        and not line.startswith("-e ")
        and line.split("==", 1)[0].lower() not in DEFAULT_EXCLUDED_PACKAGES
    ]
    return lock_header() + "\n".join(sorted(lines, key=str.lower)) + "\n"


def read_existing_lock(path: Path) -> str:
    if not path.exists():
        return ""

    raw_content = path.read_bytes()
    for encoding in ("utf-8", "utf-8-sig", "utf-16"):
        try:
            return raw_content.decode(encoding)
        except UnicodeDecodeError:
            continue
    raise UnicodeDecodeError(
        "requirements.lock.txt",
        raw_content,
        0,
        len(raw_content),
        "unsupported lock file encoding",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update requirements.lock.txt from the current Python environment."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_root() / "requirements.lock.txt",
        help="Lock file path to write.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with an error if the lock file is not up to date.",
    )
    parser.add_argument(
        "--allow-system",
        action="store_true",
        help="Allow running outside a virtual environment.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not is_virtual_environment() and not args.allow_system:
        raise SystemExit(
            "Refusing to update requirements.lock.txt outside a virtual "
            "environment. Use the project venv or pass --allow-system explicitly."
        )

    content = collect_freeze()
    output = args.output.resolve()

    if args.check:
        existing = read_existing_lock(output)
        if existing != content:
            raise SystemExit(f"{output} is not up to date.")
        return 0

    output.write_bytes(content.encode("utf-8"))
    print(f"Updated {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
